// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ToyAPI.Data;

#nullable disable

namespace ToyAPI.Migrations
{
    [DbContext(typeof(ToyDbContext))]
    partial class ToyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyAPI.Models.Brinquedo", b =>
                {
                    b.Property<int>("IdBrinquedo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Id_brinquedo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBrinquedo"));

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("Classificacao");

                    b.Property<string>("NomeBrinquedo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("Nome_brinquedo");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Preco");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("Tamanho");

                    b.Property<string>("TipoBrinquedo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("Tipo_brinquedo");

                    b.HasKey("IdBrinquedo");

                    b.ToTable("TDS_TB_Brinquedos");
                });
#pragma warning restore 612, 618
        }
    }
}
